"""Initial Migration

Revision ID: 374c17ce6730
Revises: 
Create Date: 2025-12-22 12:09:59.524403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374c17ce6730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_table',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('follower_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like_table',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tweet_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('time', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('tweeting', sa.String(length=256), nullable=False),
    sa.Column('posttime', sa.String(length=128), nullable=False),
    sa.Column('tweetimage', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    op.create_table('x_db',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('dob', sa.String(length=128), nullable=False),
    sa.Column('passwordacc', sa.String(length=256), nullable=False),
    sa.Column('profileimage', sa.String(length=256), nullable=True),
    sa.Column('coverimage', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x_db')
    op.drop_table('tweets')
    op.drop_table('notification')
    op.drop_table('like_table')
    op.drop_table('follow_table')
    # ### end Alembic commands ###
