"""Had to create new table for the tempcodedb

Revision ID: 4db03c3c3d67
Revises: dd01a7a9a6f0
Create Date: 2026-01-15 17:31:17.248012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db03c3c3d67'
down_revision = 'dd01a7a9a6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempcodedb',
    sa.Column('user_mail', sa.String(), nullable=False),
    sa.Column('user_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempcodedb')
    # ### end Alembic commands ###
