"""Updated the tweet column with username

Revision ID: dd01a7a9a6f0
Revises: 374c17ce6730
Create Date: 2025-12-27 20:29:31.305089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd01a7a9a6f0'
down_revision = '374c17ce6730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=256), nullable=False, server_default='unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
